language: php
php:
  - "7.2"

sudo: false

addons:
  chrome: stable

env:
  - TRAVIS_NODE_VERSION="12"

matrix:
  fast_finish: true

before_script:
  - google-chrome --version
  - /bin/bash scripts/travis.sh

script:
  - composer test
