name: Deploy blog
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:

jobs:
  build:
    name: Deploy blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "DEPLOY=1" >> "$GITHUB_ENV"
          else
            echo "DEPLOY=0" >> "$GITHUB_ENV"
          fi

      - uses: ./deploy/
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          DIST_ID: ${{ secrets.DIST_ID }}
          API_URL: ${{ secrets.API_URL }}
          DISQUS_XML_URL: ${{ secrets.DISQUS_XML_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
