name: Deploy blog
on: repository_dispatch

jobs:
  build:
    name: Deploy blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./deploy/
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          DIST_ID: ${{ secrets.DIST_ID }}